---
name: Bazel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup and Cache Bazel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Restore Bazel Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-cache-${{ github.ref }}-
            bazel-cache-

      # - name: Warm up Bazel Cache
      #   run: bazel build //... || true

      - name: Save Bazel Cache
        if: always()
        run: bazel shutdown

  bazel-build:
    name: Build all targets
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Bazel Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-cache-${{ github.ref }}-
            bazel-cache-

      - name: Build all targets
        run: bazel build //...

      - name: Save Bazel Cache
        if: always()
        run: bazel shutdown

  bazel-test:
    name: Run Bazel Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Bazel Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-cache-${{ github.ref }}-
            bazel-cache-

      - name: Run Bazel tests
        run: bazel test //...

      - name: Save Bazel Cache
        if: always()
        run: bazel shutdown

  format-check:
    name: Run Format Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Bazel Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            bazel-cache-${{ github.ref }}-
            bazel-cache-

      - name: Run Format Check
        run: bazel run //:format.check

      - name: Save Bazel Cache
        if: always()
        run: bazel shutdown
